/* rmk-memory.x for nRF52833 with noswap — generated by rmk-boot/build.rs
 *
 * Provides the MEMORY layout (absolute XIP addresses) and the standard
 * embassy-boot `__bootloader_*` partition symbols (flash-relative offsets)
 * consumed by partitions_from_linkerscript().
 *
 * If your board has a different flash size, replace this file with the
 * matching variant from the rmk-boot releases:
 *   https://github.com/rmk-rs/rmk-boot/releases
 */

MEMORY {
  FLASH : ORIGIN = 0x00007000, LENGTH = 462848   /* ACTIVE region */
  RAM   : ORIGIN = 0x20000000, LENGTH = 131072                 /* SRAM */
}

/* Bootloader partition symbols — offsets relative to flash start.
 * The active/state/dfu names match embassy-boot's from_linkerfile_blocking(),
 * storage is an RMK extension.
 */
__bootloader_state_start   = 0x6000;
__bootloader_state_end     = 0x7000;
__bootloader_active_start  = 0x7000;
__bootloader_active_end    = 0x78000;
__bootloader_dfu_start     = 0x0;
__bootloader_dfu_end       = 0x0;
__bootloader_storage_start = 0x78000;
__bootloader_storage_end   = 0x80000;
